- name: Init Playbook # This playbook resets MikroTik devices and assingns IP addresses to connected ports
  hosts: mikrotiks
  connection: local
  gather_facts: no
  vars:
    default_user: admin
    default_password: "''"
    new_user: ansible
    new_password: ansible
    username: admin
    password: ""
  roles:
    - default