- name: Mikrotik TEST
  hosts: all
  connection: local
  gather_facts: no
  vars:
    username: ansible
    password: ansible
  tasks:
  - name: Clear MikroTik Configuration
    mt_clean: username={{username}} mac_addr={{Source-MAC}} password={{password}}
