- name: Mikrotik TEST
  hosts: Router1
  connection: local
  gather_facts: no
  vars:
    dhcp_pool: testpool
    username: admin
    password: ""

  tasks:
  - name: DNS Setup
    mt_dns: username={{username}} hostname={{IP}} password={{password}}
      servers="192.168.50.1"
      remote_requests="false"
  - name: IP address setup
    mt_ip: username={{username}} hostname={{IP}} password={{password}}
      address={{et2addr}}
      interface=ether2
      comment="et2-ip"
  - name: Add bridge interface
    mt_brctl: username={{username}} hostname={{IP}} password={{password}}
      names=bridge-local
      interfaces=ether2
  - name: Set static route
    mt_static_route: username={{username}} hostname={{IP}} password={{password}}
      dst_address=192.168.10.0/24
      gateway=192.168.10.10
      comment="Some network"
  - name: Source NAT
    mt_nat: username={{username}} hostname={{IP}} password={{password}}
      out_interface=ether1
      chain=srcnat
      action=masquerade
  - name: Port Forwarding to machine SSH
    mt_nat: username={{username}} hostname={{IP}} password={{password}}
      chain=dstnat
      action=dst-nat
      dst_port=8023
      to_addresses="192.168.116.22"
      to_ports=23
      protocol=tcp
      comment=Telnet
  - name: Enable RIP protocol
    mt_rip: username={{username}} hostname={{IP}} password={{password}}
      interfaces=ether1,bridge0
      redistribute_connected="true"
