- name: Mikrotik TEST
  hosts: Router1
  connection: local
  gather_facts: no
  tasks:
  - name: RIP setup
    mt_rip: username={{username}} hostname={{IP}} password={{password}} interfaces=ether1,ether2 networks="192.168.116.0/24" send=v2 receive=v2 authentication=md5 authentication_key=mikrotik
  - name: Configure brigde
    mt_brctl: username={{username}} hostname={{IP}} password={{password}} interfaces=ether2 names=bridge0,bridge2 disabled="false"